import type { Metadata } from 'next'
import { IBM_Plex_Sans_KR } from 'next/font/google'
import './globals.scss'
import Navbar from '@/components/Navbar/Navbar'

const ibm = IBM_Plex_Sans_KR({ subsets: ['latin'], weight: ["100", "200", "300", "400"] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={ibm.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
